### ISSUE TITLE
Update via Pull request or Issue?

### ISSUE THREAD

**Issue by joerglohrer** [patrickrobrecht/kirchen-im-web#56]
Hi Patrick,
Meinst du man könnte den Datensatz als JSON direkt im Git integrieren (oder habe ich ihn übersehen)?
Dann könnten neben der Formulareingabe die Änderungen einfach als Pull Request oder Issue eingereicht werden.

**Comment by patrickrobrecht** [comment]
Hi Jörg,

für diejenigen, die ihre Gemeinde bei uns einreichen wollen, (i. d. R. ja Verantwortliche für die Öffentlichkeitsarbeit auf der jeweiligen Ebene, nicht notwendigerweise mit einem technischen Hintergrund) dürfte die Einreichung per Formular deutlich einfacher sein als per Pull Request mit JSON-Format, daher sehe ich nicht wirklich den Use Case aus Benutzersicht.

Zumal den Pull Request ja dann auch immer noch jemand prüfen und in die Produktivumgebung deployen müsste (wie auch immer der Datensatz angelegt wird).

Der aktuelle Workflow ist: Nach dem Absenden des Formulars werden die Daten in die Datenbank geschrieben (Geokoordinaten vorher per API ermittelt) und der Eintrag ist direkt freigeschaltet. Ich bekomme eine E-Mail-Benachrichtigung, die einen Link zu dem Eintrag enthält. Den prüfe ich kurz dahingehend, dass dort kein Quatsch drin steht. Wenn doch, lösche ich das (mangels Oberfläche direkt in der Datenbank) - ist aber bisher nur bei Duplikaten vorgekommen.
